
services:
  postgres:
    image: postgres:16
    container_name: colmeia-postgres
    environment:
      POSTGRES_DB: colmeia_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
